export const MAILLINK = "mailto:admin@hidamarikenshusenta.com"
export const WALINK = "https://api.whatsapp.com/send?phone=62881025220845&text=Halo%20LPK%20Hidamari%20Kenshu%20Senta"
export const IGLINK = "https://www.instagram.com/"
export const FBLINK = "https://www.facebook.com/"
export const LINKEDINLINK = "https://www.linkedin.com/"